### ISSUE TITLE
Please add brotli support

### ISSUE THREAD

**Issue by szepeviktor** [h5bp/server-configs-apache#105]
`AddOutputFilterByType BROTLI ...`

https://github.com/kjdev/apache-mod-brotli/issues/8

Thanks.

**Comment by XhmikosR** [comment]
@szepeviktor: can you make a PR which has it commented out but works with gzip fallback and CC me?

**Comment by szepeviktor** [comment]
The only help I've found is https://www.tunetheweb.com/performance/brotli/
It suggests to put both `AddOutputFilterByType` after each other.
Even https://httpd.apache.org/docs/trunk/mod/mod_brotli.html does not talk about fallback.

**Comment by szepeviktor** [comment]
Apache docs page has a single comment:

> It would be great to provide a description (incl. example) of how to configure the brotli compression with the fallback to gzip (e.g. depending on what the client is capable of).

**Comment by szepeviktor** [comment]
I suspect the only way is to try it.

**Comment by szepeviktor** [comment]
`AddOutputFilterByType BROTL`I seems to work:

wget --header="Accept-Encoding: gzip" produces `Content-Encoding: gzip`

wget --header="Accept-Encoding: br" `Content-Encoding: br`

**Comment by alrra** [comment]
Some considerations:

* `mod_brotli` is only included with Apache v2.4.26+ (and most people are probably not using Apache v2.4.26+ yet).

* `mod_brotli` re-compresses the content each time a request is made, and since Brotli can take more time (especially for higher compression quality levels), that can decrease performance.

---
 
So, while `mod_brotli` (especially if configured to use lower compression quality levels) may be a used for dynamic resources, for static resources one should just compress them as part of the build step and then configure Apache to serve the Brotli compressed version of those files (the same goes for Zopfli, for which Apache doesn't even have a module).
  
Here is a configuration I came up with:

https://sonarwhal.com/docs/user-guide/rules/http-compression/#how-to-configure-the-server-to-pass-this-rule

(Note: re-setting all the media types can be avoided if, for example, a convention such as `brotli-<filename>.<file-extension>` is used, however, most build tools will generated `<filename>.br`)

**Comment by XhmikosR** [comment]
@alrra: great info! Is there any way you could add it here? Maybe as it is since it's not supposed to be used on the fly like the current implementation.

**Comment by alrra** [comment]
@XhmikosR When I have some time, I want to look also into some things regarding the "on the fly" aspect, and after that I'll open a PR.

**Comment by Malvoz** [comment]
With the risk of going off-topic, there is a gzip/brotli contender called [zstd](http://facebook.github.io/zstd/) (short for Zstandard) that might be of interest aswell.

I opened an [issue for data support on caniuse](https://github.com/Fyrd/caniuse/issues/4065).
