### ISSUE TITLE
Remove "ServerTokens Prod" setting

### ISSUE THREAD

**Issue by creopard** [h5bp/server-configs-apache#153]
This setting simply can't be set in .htaccess, but only in httpd.conf file according to Apache's specification:
http://httpd.apache.org/docs/2.2/en/mod/core.html#servertokens
Doing so will just result in an 500 internal error.

The spec's line "Context:" at "ServerTokens Directive" only lists "server config" but not ".htaccess"

**Comment by LeoColomb** [comment]
That's why there is a warning, right? ;)

https://github.com/h5bp/server-configs-apache/blob/master/src/security/server_software_information.conf#L19

**Comment by LeoColomb** [comment]
Honestly I don't know. [Related commits](https://github.com/h5bp/server-configs-apache/search?q=ServerTokens&type=Commits) are not very verbose.

That say this may help to resolve #1.

**Comment by Malvoz** [comment]
I don't think h5bp wants to assume a user does or does not have access to the main server configuration file. The current approach informs users _with_ access to the main config file the availability of `ServerTokens`, and clearly states to not use it if you don't.

However (unrelated to `ServerTokens` but related to comments on main config file), the [comment](https://github.com/h5bp/server-configs-apache/blob/ea022f440ed4c50dbfa0acc6194c06ddefcbc666/dist/.htaccess#L4) about avoiding `.htacces`s should also recommend setting `AllowOverride` to not allow `.htaccess` because: 

> When AllowOverride is set to allow the use of .htaccess files, httpd will look in every directory for .htaccess files. Thus, permitting .htaccess files causes a performance hit, whether or not you actually even use them!

_https://httpd.apache.org/docs/2.4/howto/htaccess.html#when_

**Comment by XhmikosR** [comment]
Yeah, I'd say this should stay as is for the aforementioned reasons.

**Comment by LeoColomb** [comment]
Agreed, closing.
@Malvoz Feel free to open a PR to add this recommendation. 👍
