### ISSUE TITLE
Use environment variable "no-brotli" in RewriteRule for pre-compressed brotli content

### ISSUE THREAD

**Issue by warrenski** [h5bp/server-configs-apache#158]
In the block of config for pre-compressed brotli content, the `RewriteRule` refers to the `no-gzip` environment variable. This is incorrect and should actually be:

`RewriteRule \.br$ - [E=no-brotli:1]`

Source: https://httpd.apache.org/docs/2.4/mod/mod_brotli.html#enable

**Comment by LeoColomb** [comment]
Thanks for your report, @warrenski! 👍 

`no-gzip` is intentional here, to prevent `mod_deflate` gziping content before sending, as explained by the comment just before:

https://github.com/h5bp/server-configs-apache/blob/9481d537d60d0226667a2f9712018a1ff4d799d8/src/web_performance/pre-compressed_content_brotli.conf#L20-L21

`no-brotli` could be added, but `mod_brotli` module:
* Is not part of the default distribution package, at least for now.
* Need to [be enable for each MIME-type](https://httpd.apache.org/docs/current/mod/mod_brotli.html#enable) (like gzip but with different header).
* Is not that recommended for some reasons, mostly performance (eg. https://github.com/h5bp/server-configs-apache/issues/105#issuecomment-363739736).

**Comment by warrenski** [comment]
Thank you for the explanation @LeoColomb - I see that you are correct.
