### ISSUE TITLE
Protect cookies with HTTPOnly flag

### ISSUE THREAD

**Issue by broros** [h5bp/server-configs-apache#172]
```
<IfModule mod_headers.c>
    Header edit Set-Cookie ^(.*)$ $1;HttpOnly;Secure
</IfModule>
```

**Comment by hans2103** [comment]
reason: 
Implement cookie HTTP header flag with HTTPOnly & Secure to protect website from XSS attacks

According to the documentation of mod_headers the argument `edit` is available in Apache version 2.2.4 and later.
source: https://httpd.apache.org/docs/2.2/mod/mod_headers.html#page-header)

To use HttpOnly and Secure flag in a previous version you can use:
```
Header set Set-Cookie HttpOnly;Secure
```
(source: https://geekflare.com/httponly-secure-cookie-apache/)

**Comment by LeoColomb** [comment]
Thanks for your report, @broros & @hans2103! 👍 

That said, I wonder if this header is not too application's area related.

**Comment by XhmikosR** [comment]
It definitely is specific to the project, because this prevents manipulating the cookies client side IIRC.

**Comment by LeoColomb** [comment]
You're right. Then we're opened for a PR to add a new file with this directive! 👍

**Comment by XhmikosR** [comment]
@LeoColomb: I meant, it's specific for each use case, not to this repo. :)

**Comment by LeoColomb** [comment]
Ah, OK 😉, sorry for misunderstanding! 😇
So I agree, closing.

**Comment by XhmikosR** [comment]
A PR adding this as a comment, doesn't sound too bad though. As long as the downsides and upsides are clearly noted.

**Comment by Malvoz** [comment]
@XhmikosR @LeoColomb 

Many developers read and write cookies using JS, so `HttpOnly` would probably be a frustrating default. However because there is now a specification for cookie eviction ([EAT Cookies](https://tools.ietf.org/html/draft-thomson-http-omnomnom)) which asks UA's to **treat all non-secure cookies as session cookies** I think it'd be nice to at least add a comment on this including a note on recommending setting the `Secure` directive to prevent such eviction.

Also, there are some caveats to consider with how developers set cookies and then editing those on-the-fly (e.g. directives being set multiple times or double semicolons), see https://www.tunetheweb.com/security/http-security-headers/secure-cookies/

**Comment by broros** [comment]
Mozilla observatory requires cookies header to be set, so I think it's kind of important

https://observatory.mozilla.org/

**Comment by Malvoz** [comment]
@broros I think what you mean is that they look for: "_All cookies use the `Secure` flag and all session cookies use the `HttpOnly` flag_".
