### ISSUE TITLE
Build script missing when installing via npm

### ISSUE THREAD

**Issue by tomkyle** [h5bp/server-configs-apache#197]
Just installed the package via _npm_ and tried to call the **build.sh** script. It's missing.

In fact, **package.json**'s `file` entry tells npm to only copy the `dist/.htaccess`. I think, adding the `bin/`directory would be useful. What do you think?

**Comment by LeoColomb** [comment]
Thanks for opening this issue, @tomkyle!

That said, we expect that the npm version of this repo will only distribute the build artifacts, here `dist/.htaccess`.

We may consider adding `bin/`, but then `src/` too, and basically the whole repo.
IMHO make use of GitHub releases assets is much more relevant because these files have nothing to do in a Node.js env or even in a javascript env.

**Comment by LeoColomb** [comment]
I'm closing this issue for invalid and inactive, but please don't hesitate to continue the discussion below.
