### ISSUE TITLE
compression and expires headers not working

### ISSUE THREAD

**Issue by broros** [h5bp/server-configs-apache#202]
doing testing at:
https://tools.pingdom.com

compression with gzip  and expires headers is not registering 

```
F | Compress components with gzip
F | Add Expires headers
```
<img width="1141" alt="Screenshot 2019-09-25 at 9 48 39 PM" src="https://user-images.githubusercontent.com/598228/65658984-ab3ac500-dfde-11e9-90e7-5ac096bef0e3.png">

**Comment by LeoColomb** [comment]
Thanks for this ticket @broros.

Looks like the config is not well configured on your server. 
Please check if your config is at the right place and working correctly, and all wanted options are enabled. 

If everything is fine about the config, verify logs don't report any error and contact your host' support.

**Comment by broros** [comment]
the file gets included as I see it responding when I make changes, however, Expires headers  options does not respond,  the file is inside etc/apache2/ in the server configuration directory

debian 10

**Comment by LeoColomb** [comment]
Some httpd modules are requested, please check them.
https://github.com/h5bp/server-configs-apache/tree/9ae931cfe5bc4fe8af0fca21094ad93d4437cfaa#usage

Bear in mind these configuration files are present in this repo since many years and used by many (many) server, I doubt the errors you reported comes from the templates of this repo.

**Comment by broros** [comment]
all the modules listed are enabled

**Comment by broros** [comment]
I copied the template as is
