### ISSUE TITLE
Add `Cross-Origin-Embedder-Policy` and `Cross-Origin-Opener-Policy`

### ISSUE THREAD

**Issue by summercms** [h5bp/server-configs-apache#250]
Please can you add `Cross-Origin-Embedder-Policy` and `Cross-Origin-Opener-Policy` to the `/h5bp/security/` section.

More info: https://web.dev/coop-coep/

More info: https://developers.google.com/web/updates/2020/10/devtools#frame-details

As we want to add it to the apache header list.

**Comment by LeoColomb** [comment]
Thanks for opening this issue @ayumi-cloud!
These two headers are interesting!
Is there any living standard and some official documentation?

**Comment by ayumi-cloud** [comment]
@LeoColomb 

> Is there any living standard and some official documentation?

Yes there is, it has been added to the html spec found here: 

https://html.spec.whatwg.org/multipage/origin.html#coep
https://html.spec.whatwg.org/multipage/origin.html#cross-origin-opener-policies

Also MDN Links are as follows:

https://developer.cdn.mozilla.net/en-US/docs/Web/HTTP/Headers/Cross-Origin-Embedder-Policy
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Opener-Policy

Hope that helps.

**Comment by LeoColomb** [comment]
https://caniuse.com/mdn-http_headers_cross-origin-embedder-policy
https://caniuse.com/mdn-http_headers_cross-origin-opener-policy

---

Thanks @ayumi-cloud!

Looks good to me. Could you open a PR for this?
Thanks again!

**Comment by Malvoz** [comment]
There are 2 other headers that relate and ought to be considered: `Cross-Origin-Resource-Policy` and `Origin-Isolation`.

**`Cross-Origin-Resource-Policy`**([spec](https://fetch.spec.whatwg.org/#cross-origin-resource-policy-header), [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Resource-Policy)):

The header can, for example, be used to restrict cross-origin access to resources that would otherwise be accessible by default and not restricted per the [same-origin policy](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy). Sort of a standard for [preventing hotlinking](https://perishablepress.com/creating-the-ultimate-htaccess-anti-hotlinking-strategy/).

For example, when COEP (`Cross-Origin-Embedder-Policy`) is set to `require-corp`, an embedded cross-origin resource should respond with `Cross-Origin-Resource-Policy: cross-origin`, or it'd be blocked.

This header can apply to any resource.

**`Origin-Isolation`** ([spec](https://html.spec.whatwg.org/multipage/origin.html#origin-isolation)):

`Origin-Isolation` is a related header, it's not supported in browsers yet (outside of origin trials I think), see [Chrome status](https://chromestatus.com/feature/5683766104162304). The WICG [`Origin-Isolation` explainer](https://github.com/WICG/origin-isolation#coop--coep) says:

> Deploying `COOP` + `COEP` can be a significant burden for sites, e.g. in terms of how it requires all of their embedded content to be updated with `CORP`, `COEP`, and `COOP` headers.

> this separate header would be much easier to deploy than `COOP` + `COEP`, since it does not require any embeddee cooperation.

This header, as well as COEP and COOP should probably apply to the same resources as [CSP](https://github.com/h5bp/server-configs-apache/blob/069a96debf5797c128434b7b18042e8cd97074ce/h5bp/security/content-security-policy.conf#L78) (i.e. `expr=%{CONTENT_TYPE} =~ m#text\/(html|javascript)|application\/pdf|xml#i`). Although it doesn't seem to make sense to respond with COEP in PDF files as they cannot embed other files.

> More info: https://web.dev/coop-coep/

Also see https://web.dev/why-coop-coep/ and:
- https://isolated.website/
- https://resourcepolicy.fyi/.

**Comment by ayumi-cloud** [comment]
I had 4 headers written down as this:

 - COEP: Cross Origin Embedder Policy

 - COOP: Cross Origin Opener Policy

 - CORP: Cross Origin Resource Policy

 - CORB: Cross Origin Read Blocking

I think I didn't include all 4 as I thought only 2 were ready to use and not under a flag? But it would be nice to add them all.

> This header, as well as COEP and COOP should probably apply to the same resources as CSP (i.e. expr=%{CONTENT_TYPE} =~ m#text\/(html|javascript)|application\/pdf|xml#i). Although it doesn't seem to make sense to respond with COEP in PDF files as they cannot embed other files.

Yah I was thinking would be nice to write it like that. Don't forget they also use the `reporting` api, see here: https://developers.google.com/web/updates/2020/10/devtools#frame-details

I did send some messages to some security experts to see if they could add these headers to their tools and see how they would try and write the header including their reporting api tools?

---

Not sure how to best code a pr for this?

If someone wants to give it a go - please go ahead.

**Comment by Malvoz** [comment]
@ayumi-cloud https://github.com/h5bp/server-configs-apache/issues/250#issuecomment-712943315
> CORB: Cross Origin Read Blocking

[CORB](https://fetch.spec.whatwg.org/#corb) is a concept (see [CORB for developers](https://www.chromium.org/Home/chromium-security/corb-for-developers)).

> Don't forget they also use the `reporting` api

I think generally H5BP doesn't or at least have not supported reporting headers in the past, maybe that could be a new category `/h5bp/reporting/`, feel free to open an issue on that.

**Comment by ayumi-cloud** [comment]
Thanks for the link! Going to read that and watch the video later today.

Would it be a good idea just to mention the `reporting` api in the description notes instead of creating a separate section? 

Because the reporting api seems to just extend these headers and allow a user to receive messages when the policy has been broken etc.

Then users would be aware that they can extend the header(s) with the reporting api with their own custom setups and the reporting api is beyond the scope of this repo's project (to include them directly).

**Comment by LeoColomb** [comment]
> I think generally H5BP doesn't or at least have not supported reporting headers/directives in the past, but feel free to open an issue on that.

Indeed, as reporting usually refers to private endpoints, it is hard to used them directly here.

---

At the end, what do you both recommend? Documentation? Configuration addition?

**Comment by ayumi-cloud** [comment]
Going take a stab at this:

1. Set the Cross-Origin-Opener-Policy

```
<IfModule mod_headers.c>
    Header set Cross-Origin-Opener-Policy "same-origin"
</IfModule>
```

2. Set the Cross-Origin-Resource-Policy

```
<IfModule mod_headers.c>
    # (1) If the resource is expected to be loaded only from the same origin
    Header set Cross-Origin-Resource-Policy "same-origin"

    # (2) If the resource is expected to be loaded only from the same site but cross origin
    Header set Cross-Origin-Resource-Policy "same-site"

    # (3) If the resource is loaded from cross origin(s) under your control
    Header set Cross-Origin-Resource-Policy "cross-origin"
</IfModule>
```

3. For sending reports using the reporting api use the header

```
Cross-Origin-Embedder-Policy-Report-Only
```

For more details see your service provider as the reporting api usually refers to private endpoints.

4. Enable COEP

```
<IfModule mod_headers.c>
    Header set Cross-Origin-Embedder-Policy "require-corp"
</IfModule>
```

Please adjust and update this, but at least this starts the ball rolling...
